### ISSUE TITLE
Attachment of Youtube link for learning GitHub

### ISSUE THREAD

**Issue by Siddarthan-S** [sidd-005/Learning_GitHub#5]
Dear Sidd-005,
You are learning GitHub well. This youtube Channel would be useful for you to learn GitHub and I'm attaching the youtube link to watch the LEARN AUTOMATION ONLINE [https://youtu.be/iXEyRACiGdA](url) channel videos.

**Comment by sidd-005** [comment]
Dear Siddarthan,
Thanks for suggesting this video.
